### ISSUE TITLE
Delivery estimates in order Page and Email

### ISSUE THREAD

**Issue by vishalsanghi** [skyverge/woocommerce-shipping-estimate#13]
Hello

I liked the plugin and great work. Simple and sweet. I am using it now however, when my order is generated my customers are not able to see delivery estimates in either email or View order page in my account. This is post placing the order can you please help if possible.

Regards
Vishal Sanghi

**Comment by bekarice** [comment]
@vishalsanghi glad to hear this has been helpful! thanks for sharing this feedback. :)

I'm afraid estimates are only available in the cart / checkout. we don't plan to expand the plugin further at this time to include estimates elsewhere, so I'm going to close this issue since it's out of scope for the project.
