### ISSUE TITLE
Fatal error while updating to WooCommerce 4.3

### ISSUE THREAD

**Issue by pacmanito** [skyverge/woocommerce-shipping-estimate#25]
While updating to WooCommerce 4.3 I got a fatal error related to this plugin
![wc shipping error](https://user-images.githubusercontent.com/56888134/88139029-924b7200-cbf7-11ea-921d-8af0fbd8194f.jpg)
The site was not working until I renamed plugin directory. Please look into this.

**Comment by wvega** [comment]
Hey @pacmanito, thank you for reporting that error and I'm sorry our plugin caused problems on your website.

I was able to reproduce the Fatal error when I manually deactivated WooCommerce, for example to delete it, and replace it with a newer version. I didn't get a Fatal error when I used the `update now` link.

Would you be able to confirm that you saw this error after deactivating WooCommerce? I want to be sure we are looking at the same problem.

Thanks,

**Comment by pacmanito** [comment]
Nope actually. I was just updating WooCommerce as usual through wp-admin/update-core.php page. However AFAIK the plugin is deactivated throughout update process.

**Comment by wvega** [comment]
Thank you for the additional details @pacmanito. I haven't been able to reproduce that scenario locally, but since I got the same Fatal error when I deactivated the plugin manually, that should be enough to add a fix.

I think we already fixed the underlying problem here: https://github.com/skyverge/wc-jilt-promotions/pull/1. The next step is to update the Shipping Estimates plugin to use that version. I'll create an internal story to do that as soon as possible.

**Comment by pacmanito** [comment]
In the meantime I got absolutely the same fatal error while updating to WooCommerce 4.3.1.

**Comment by unfulvio** [comment]
Apologies, @pacmanito we did fix the issue in the library included in the plugin but we have yet to release a new version of the plugin to update it with the patched version -- sorry for the trouble, we should do that next

**Comment by pacmanito** [comment]
Please update the version of plugin provided through SkyVerge website.
